import { IGenerator, ProjectConfig } from './types';
import { mkdir, writeTextFile } from '@tauri-apps/plugin-fs';

export class NodeGenerator implements IGenerator {
    async scaffold(path: string): Promise<void> {
        await mkdir(path, { recursive: true });
        await mkdir(`${path}/src`, { recursive: true });
    }

    async createManifest(config: ProjectConfig): Promise<void> {
        const packageJson = {
            name: config.projectName,
            version: "0.0.1",
            description: "Generated by Ggami Builder",
            scripts: {
                "start": "node src/main.js"
            },
            dependencies: {
                "express": "^4.18.2"
            }
        };
        await writeTextFile(`${config.targetPath}/package.json`, JSON.stringify(packageJson, null, 2));
    }

    async generateCode(config: ProjectConfig): Promise<void> {
        const appjs = `
const express = require('express');
const app = express();
const port = 3000;

app.get('/', (req, res) => {
  res.send('Hello from Node.js (Generated by Ggami)!');
});

app.listen(port, () => {
  console.log(\`Example app listening on port \${port}\`)
});
`;
        await writeTextFile(`${config.targetPath}/src/main.js`, appjs);
    }
}
