package generator

import (
	"encoding/json"
	"os"
	"path/filepath"
)

// NodeGenerator implements the Generator interface for Node.js projects
type NodeGenerator struct{}

func (n *NodeGenerator) Scaffold(path string) error {
	dirs := []string{
		path,
		filepath.Join(path, "src"),
	}
	for _, dir := range dirs {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return err
		}
	}
	return nil
}

func (n *NodeGenerator) CreateManifest(config ProjectConfig) error {
	pkg := map[string]interface{}{
		"name":        config.ProjectName,
		"version":     "0.0.1",
		"description": "Generated by Ggami Builder",
		"scripts": map[string]string{
			"start": "node src/main.js",
		},
		"dependencies": map[string]string{
			"express": "^4.18.2",
		},
	}

	data, err := json.MarshalIndent(pkg, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(config.TargetPath, "package.json"), data, 0644)
}

func (n *NodeGenerator) GenerateCode(config ProjectConfig) error {
	appJS := `
const express = require('express');
const app = express();
const port = 3000;

app.get('/', (req, res) => {
  res.send('Hello from Node.js (Generated by Ggami)!');
});

app.listen(port, () => {
  console.log(` + "`" + `Example app listening on port ${port}` + "`" + `)
});
`
	return os.WriteFile(filepath.Join(config.TargetPath, "src", "main.js"), []byte(appJS), 0644)
}
