// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddComponent(arg1, arg2) {
  return window['go']['main']['App']['AddComponent'](arg1, arg2);
}

export function CreateBuilderProject(arg1) {
  return window['go']['main']['App']['CreateBuilderProject'](arg1);
}

export function DeleteComponent(arg1, arg2) {
  return window['go']['main']['App']['DeleteComponent'](arg1, arg2);
}

export function ExportBuilderHTML() {
  return window['go']['main']['App']['ExportBuilderHTML']();
}

export function GenerateProject(arg1, arg2) {
  return window['go']['main']['App']['GenerateProject'](arg1, arg2);
}

export function GetCurrentProject() {
  return window['go']['main']['App']['GetCurrentProject']();
}

export function GetModules() {
  return window['go']['main']['App']['GetModules']();
}

export function LoadBuilderProject() {
  return window['go']['main']['App']['LoadBuilderProject']();
}

export function ReorderComponents(arg1, arg2) {
  return window['go']['main']['App']['ReorderComponents'](arg1, arg2);
}

export function SaveBuilderProject() {
  return window['go']['main']['App']['SaveBuilderProject']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function UpdateComponent(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateComponent'](arg1, arg2, arg3);
}
