// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {builder} from '../models';
import {generator} from '../models';
import {modules} from '../models';

export function AddComponent(arg1:string,arg2:builder.Component):Promise<void>;

export function CreateBuilderProject(arg1:string):Promise<builder.BuilderProject>;

export function DeleteComponent(arg1:string,arg2:string):Promise<void>;

export function ExportBuilderHTML():Promise<void>;

export function GenerateProject(arg1:generator.ProjectConfig,arg2:string):Promise<Record<string, any>>;

export function GetCurrentProject():Promise<builder.BuilderProject>;

export function GetModules():Promise<Array<modules.ModuleDef>>;

export function LoadBuilderProject():Promise<builder.BuilderProject>;

export function ReorderComponents(arg1:string,arg2:Array<string>):Promise<void>;

export function SaveBuilderProject():Promise<void>;

export function SelectDirectory():Promise<string>;

export function UpdateComponent(arg1:string,arg2:string,arg3:builder.Component):Promise<void>;
